name: 'Setup'
description: 'Setup NPM Environment'
inputs:
  node-version:
    description: 'Version of node to use'
    required: false
    default: 18

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      shell: bash
