apiVersion: v1
kind: Namespace
metadata:
  name: mas-slm
  labels:
    security.openshift.io/scc.podSecurityLabelSync: "false"
    openshift.io/run-level: "0"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mas-slm-app
  name: mas-slm-app
  namespace: mas-slm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mas-slm-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mas-slm-app
    spec:
      serviceAccountName: mas-slm-service-account
      containers:
        - name: main
          imagePullPolicy: Always
          image: rojanjose/tcmax:latest
          command: ["npm", "run", "dev"]
          securityContext:
            runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: mas-slm-svc
  namespace: mas-slm
spec:
  clusterIP: 172.21.192.191
  clusterIPs:
    - 172.21.192.191
  internalTrafficPolicy: Cluster
  ports:
    - name: mas-slm-port
      port: 9000
    - name: https
      port: 443
      targetPort: 9443
